apiVersion: apps/v1
kind: Deployment
metadata:
  name: mind-app-getpath
  labels:
    app: mind-app-getpath
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mind-app-getpath
  template:
    metadata:
      labels:
        app: mind-app-getpath
    spec:
      containers:
      - name: mind-app-getpath
        image: eelsherif/mind-app-getpath
        ports:
        - containerPort: 8080
