apiVersion: v1
kind: Service
metadata:
  name: mind-app-getpath
spec:
  type: ClusterIP
  selector:
    app: mind-app-getpath
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
