---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
nameSuffix: -staging
resources:
- ../../../bases/mind-app-getpath
- namespace.yaml
transformers:
- labels.yaml
replicas:
- count: 1
  name:  nginx
